### ISSUE TITLE
Inkpot fails to compile on UE 5.4.2

### ISSUE THREAD

**Issue by Redthirst** [The-Chinese-Room/Inkpot#98]
Trying to build a fresh project with 5.4.2 throws out an error

![image](https://github.com/The-Chinese-Room/Inkpot/assets/9901055/cbd9ea13-875a-4371-881b-e7532a5f0073)

Building it manually through VS2022 gives this error:

`3>H:\UE_5.4\Engine\Source\Runtime\Core\Public\String\FormatStringSan.h(99): error C2338: static_assert failed: ''%s' expects `TCHAR*`; use '%hs' for `const char*`.'

`3>H:\UE_5.4\Engine\Source\Runtime\Core\Public\String\FormatStringSan.h(99): note: the template instantiation context (the oldest one first) is`

`3>H:\UnrealProjects\Parhelion\Plugins\Inkpot\Source\InkpotEditor\Private\Test\InkPlusPlusTest.cpp(738): note: see reference to class template instantiation 'UE::Core::Private::FormatStringSan::TPresentErr<1>::TErrMsg<UE::Core::Private::FormatStringSan::TAtArgPos<1>>' being compiled`

**Comment by Solessfir** [comment]
I've already made a fix PR. Meanwhile, you can get the working version here: https://github.com/Solessfir/Inkpot/releases/tag/v1.02.21

**Comment by Redthirst** [comment]
Yeah, it was me on Discord asking about it. Thanks again!

**Comment by annalee** [comment]
Heads-up, I tried the new version and am seeing the same error as above, followed by "error: [projectname] could not be compiled. Try rebuilding from source manually."

**Comment by Solessfir** [comment]
> Heads-up, I tried the new version and am seeing the same error as above, followed by "error: [projectname] could not be compiled. Try rebuilding from source manually."

Are you sure that you've got .zip file linked above?

**Comment by annalee** [comment]
v1.02.21-release, yes. I thought I might have kept the wrong file the first time so I did the following:

1. delete previous inkpot folder in plugins
2. redownload v1.02.21-release from link above
3. unzip and rename unzipped file Inkpot
4. Move it to the project's Plugins folder

But when I tried to open the project, same error as above. I also tried it in a new project just for giggles, but the same thing happened. These are both new blank projects; this is my first time installing Inkpot so I created new projects to try it out.

**Comment by Solessfir** [comment]
> v1.02.21-release, yes. I thought I might have kept the wrong file the first time so I did the following:
> 
> 1. delete previous inkpot folder in plugins
> 2. redownload v1.02.21-release from link above
> 3. unzip and rename unzipped file Inkpot
> 4. Move it to the project's Plugins folder
> 
> But when I tried to open the project, same error as above. I also tried it in a new project just for giggles, but the same thing happened. These are both new blank projects; this is my first time installing Inkpot so I created new projects to try it out.

Are you using the latest UE 5.4.2?
If so, and the issue still occurs - you can try to rebuild this plugin from source, just make sure that your project is C++ project.
If this doesn't help it's better to go to the discord (link in the readme)

**Comment by annalee** [comment]
Thanks for the quick responses and trying to help me troubleshoot--I really appreciate it.

Yes, YE 5.4.2. I'll give rebuilding the plugin a try tomorrow and swing by the discord if that doesn't do it.

**Comment by TCR-Nick** [comment]
Hi all,
This had all been fixed in the head revision, this has now all been combined into a new release. 
**v1.03.21-release**
